version: '3'
services:
        terraform: 
                build:
                  context: .
                  dockerfile: terraform.dockerfile
        flaskwebapp:
                build: 
                  context: . 
                ports:
                        - "5000:5000"

                
